bookings/api/urls.py
from django.conf.urls import url
from django.urls import path
from rest_framework.urlpatterns import format_suffix_patterns
from .views import BookingApiListView, BookingAPICreateView, BookingApiDetailView, BookingApiDestroyView, BookingApiUpdateView, BookingApiCustomerListView

urlpatterns = [
    path('', BookingApiListView.as_view(), name='api_booking'),
    path('customer/', BookingApiCustomerListView.as_view(), name='api_booking_customer'),
    url(r'^create$', BookingAPICreateView.as_view(), name='api_booking_create'),
    url(r'^(?P<pk>\d+)/$', BookingApiDetailView.as_view(), name='api_booking_detail'),
    url(r'^(?P<pk>\d+)/delete$', BookingApiDestroyView.as_view(), name='api_booking_destroy'),
    url(r'^(?P<pk>\d+)/update$', BookingApiUpdateView.as_view(), name='api_booking_update'),
]

urlpatterns = format_suffix_patterns(urlpatterns)

bookings/urls.py
from django.conf.urls import url
from django.urls import path
from rest_framework.urlpatterns import format_suffix_patterns
from .views import BookingCreateView

urlpatterns = [
    url(r'^(?P<pk>\d+)/create$', BookingCreateView.as_view(), name='booking_create'),
]

urlpatterns = format_suffix_patterns(urlpatterns)

payment/api/urls.py
from django.conf.urls import url
from django.urls import path
from rest_framework.urlpatterns import format_suffix_patterns
from .views import PaymentAPICreateView, PaymentApiCustomerListView, PaymentApiDestroyView, PaymentApiDetailView, PaymentApiListView, PaymentApiUpdateView

urlpatterns = [
    url(r'^create$', PaymentAPICreateView.as_view(), name='payment_create'),
    path('', PaymentApiListView.as_view(), name='api_booking'),
    url(r'^customer/$', PaymentApiCustomerListView.as_view(), name='api_payment_customer'),
    url(r'^(?P<pk>\d+)/$', PaymentApiDetailView.as_view(), name='api_payment_detail'),
    url(r'^(?P<pk>\d+)/delete$', PaymentApiDestroyView.as_view(), name='api_payment_destroy'),
    url(r'^(?P<pk>\d+)/update$', PaymentApiUpdateView.as_view(), name='api_payment_update'),
]

urlpatterns = format_suffix_patterns(urlpatterns)

payment/urls.py
from django.conf.urls import url
from django.urls import path
from rest_framework.urlpatterns import format_suffix_patterns
from .views import PaymentCreateView

urlpatterns = [
    url(r'^(?P<pk>\d+)/$', PaymentCreateView.as_view(), name='payment'),
]

urlpatterns = format_suffix_patterns(urlpatterns)

bookings/models.py
from django.db import models
from customer_account.models import CustomerAccount
from user.models import CustomUser
from flight.models import Flight
from seats.models import Seat
# from account.models import CustomUser
# Create your models here.

from django.urls import reverse
from django.db import models

class Booking(models.Model):
    ref = models.AutoField(primary_key=True)
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE, null=False)
    flight = models.ForeignKey(Flight, on_delete=models.CASCADE, null=False)
    seat =  models.ForeignKey(Seat, on_delete=models.CASCADE, null=False)
    timestamp   = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = (('user','flight'),('seat','flight'))

    def __str__ (self):
        return str(self.ref)

    def get_absolute_url(self):
        return u'/payment/%d/' % self.ref

payment/models.py
from django.db import models
from bookings.models import Booking
# Create your models here.


class Payment(models.Model):
    ref = models.AutoField(primary_key=True)
    booking = models.ForeignKey(Booking, on_delete=models.CASCADE, null=False, unique=True)
    payment = models.CharField(max_length=10, unique=True)

    def __str__ (self):
        return str(self.ref)

    # def get_absolute_url(self):
    #     return '/index'

bookings/forms.py
from django import forms

from .models import Booking

class BookingModelForm(forms.ModelForm):
    class Meta:
        model = Booking
        fields = [
            'user',
            'flight',
            'seat',
        ]

payment/forms.py
from django import forms

from .models import Payment

class PaymentModelForm(forms.ModelForm):
    class Meta:
        model = Payment
        fields = [
            'booking',
            'payment'
        ]

bookings/api/views.py
from rest_framework import generics
from rest_framework import permissions
from rest_framework_jwt.authentication import JSONWebTokenAuthentication
from django.db.models import Q
import datetime
from bookings.models import Booking
from flight.models import Flight

from .serializers import BookingModelSerializer

from rest_framework.authtoken.models import Token


class BookingApiCustomerListView(generics.ListAPIView):
    '''
    Get all booking for a logged in user.
    '''

    authentication_classes = (JSONWebTokenAuthentication, )
    serializer_class = BookingModelSerializer

    def get_queryset(self, *args, **kwargs):
        qs = Booking.objects.filter(user__id=self.request.user.id)
        query = self.request.GET.get("q", None)
        query_day =  self.request.GET.get("day", None)
        print(query_day)
        if query_day is not None:
            qs = qs.filter(
                Q(ref__icontains=query)
                )
        return qs


class BookingApiListView(generics.ListAPIView):
    '''
    Get all bookings made. The request user needs to be admin
    '''
    permission_classes = [permissions.IsAdminUser]
    serializer_class = BookingModelSerializer
    
    
    def get_queryset(self, *args, **kwargs):
        query = self.request.GET.get("q", None)
        query_day =  self.request.GET.get("day", None)
        print(query_day)

        qs = Booking.objects.all()
        query = self.request.GET.get("q", None)
        if query is not None:
            qs = qs.filter(
                Q(ref__icontains=query)
                )
        if query_day is not None:
            day = query_day.split(',')
            day = datetime.datetime(int(day[0]), int(day[1]), int(day[2]))
            print(day)
            qs = qs.filter(
                Q(timestamp__year=day.year, timestamp__month=day.month, timestamp__day=day.day)
                )
        return qs


class BookingAPICreateView(generics.CreateAPIView):
    '''
    Create a new booking
    '''
    serializer_class = BookingModelSerializer
    authentication_classes = (JSONWebTokenAuthentication, )


class BookingApiDetailView(generics.RetrieveAPIView):
    '''
    Get a booking details
    '''
    queryset = Booking.objects.all()
    serializer_class = BookingModelSerializer
    authentication_classes = (JSONWebTokenAuthentication, )


class BookingApiDestroyView(generics.DestroyAPIView):
    '''
    Delete a booking
    '''
    queryset = Booking.objects.all()
    serializer_class = BookingModelSerializer
    authentication_classes = (JSONWebTokenAuthentication, )


class BookingApiUpdateView(generics.UpdateAPIView):
    '''
    Update a booking
    '''
    queryset = Booking.objects.all()
    serializer_class = BookingModelSerializer
    authentication_classes = (JSONWebTokenAuthentication, )

bookings/views.py
from django.shortcuts import render

from django.urls import reverse_lazy, reverse

# Create your views here.
from django.views.generic.edit import CreateView
from .forms import BookingModelForm
from flight.models import Flight
from customer_account.models import CustomerAccount
from seats.models import Seat
from bookings.models import Booking

class BookingCreateView(CreateView):
    form_class  = BookingModelForm
    template_name = 'bookings_form.html'

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        # Add in a QuerySet of all the books
        flight = Flight.objects.get(id=self.kwargs['pk'])
        context['flight'] = flight
        context['user'] = CustomerAccount.objects.get(id=self.request.user.id)
        context['booked_seats'] = bookings = Booking.objects.filter(flight__id=flight.id)
        context['seats'] = Seat.objects.all()
        success_url = reverse_lazy("index") 
        return context

payment/api/views.py
from rest_framework import generics
from rest_framework import permissions
from rest_framework_jwt.authentication import JSONWebTokenAuthentication
from django.db.models import Q
from payment.models import Payment

from .serializers import PaymentModelSerializer

from rest_framework.authtoken.models import Token


class PaymentApiCustomerListView(generics.ListAPIView):
    '''
    Get a logged in users all payments 
    '''
    authentication_classes = (JSONWebTokenAuthentication, )
    serializer_class = PaymentModelSerializer

    def get_queryset(self, *args, **kwargs):
        qs = Payment.objects.filter(booking__user__id=self.request.user.id)
        query = self.request.GET.get("q", None)
        if query is not None:
            qs = qs.filter(
                Q(ref__icontains=query)
                )
        return qs


class PaymentApiListView(generics.ListAPIView):

    '''
    Get all payments. The request user needs to be admin
    '''
    permission_classes = [permissions.IsAdminUser]
    serializer_class = PaymentModelSerializer
    
    def get_queryset(self, *args, **kwargs):
        qs = Payment.objects.all()
        query = self.request.GET.get("q", None)
        if query is not None:
            qs = qs.filter(
                Q(ref__icontains=query)
                )
        return qs


class PaymentAPICreateView(generics.CreateAPIView):
    '''
    Create a new payment
    '''
    serializer_class = PaymentModelSerializer
    authentication_classes = (JSONWebTokenAuthentication, )


class PaymentApiDetailView(generics.RetrieveAPIView):

    '''
    Update a payment
    '''
    queryset = Payment.objects.all()
    serializer_class = PaymentModelSerializer
    authentication_classes = (JSONWebTokenAuthentication, )


class PaymentApiDestroyView(generics.DestroyAPIView):
    '''
    Delete a payment. The request user needs to be admin
    '''
    queryset = Payment.objects.all()
    serializer_class = PaymentModelSerializer
    permission_classes = [permissions.IsAdminUser]


class PaymentApiUpdateView(generics.UpdateAPIView):
    '''
    Update a payment
    '''
    queryset = Payment.objects.all()
    serializer_class = PaymentModelSerializer
    permission_classes = [permissions.IsAdminUser]

payment/views.py
from django.shortcuts import render

# Create your views here.
from django.views.generic.edit import CreateView
from .forms import PaymentModelForm
from bookings.models import Booking

class PaymentCreateView(CreateView):
    form_class  = PaymentModelForm
    template_name = 'payment_form.html'

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        booking = Booking.objects.get(ref=self.kwargs['pk'])
        context['booking'] = booking
        return context

templates/base.html
{% load static %}

<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <title>Airtech | {% block title %} {% endblock title %}</title>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'static/style.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Catamaran:100,200,300,400,500,600,700,800,900" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Lato:100,100i,300,300i,400,400i,700,700i,900,900i" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.3.0/css/datepicker.min.css" />
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.3.0/css/datepicker3.min.css" />
    <script src="https://code.jquery.com/jquery-3.3.1.js" integrity="sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60=" crossorigin="anonymous"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.3.0/js/bootstrap-datepicker.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
    {% block script %}{% endblock script %}
  </head>
  <body>
      {% if user.is_authenticated %}
	  	{% include "navbar_login.html" %}
      {% else %}
	  	{% include "navbar.html" %}
      {% endif %}
        {% block content %}
        {% endblock content %}
    <!-- </div> -->
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.js" integrity="sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  </body>
</html>

templates/bookings_form.html
{% extends "base.html"  %}
{% block script %}
    <script>
        function getParameterByName(name, url) {
            if (!url) {
              url = window.location.href;
            }
            name = name.replace(/[\[\]]/g, "\\$&");
            var regex = new RegExp("[?&]" + name + "(=([^&#]*)|&|#|$)"),
                results = regex.exec(url);
            if (!results) return null;
            if (!results[2]) return '';
            return decodeURIComponent(results[2].replace(/\+/g, " "));
        }
        $(document).ready(function(){
          var query = getParameterByName('q');
          var taskList = [];
		  var newData = {}
          var all = 0;

		  function getCookie(name) {
				var cookieValue = null;
				if (document.cookie && document.cookie !== '') {
					var cookies = document.cookie.split(';');
					for (var i = 0; i < cookies.length; i++) {
						var cookie = jQuery.trim(cookies[i]);
						// Does this cookie string begin with the name we want?
						if (cookie.substring(0, name.length + 1) === (name + '=')) {
							cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
							break;
						}
					}
				}
				return cookieValue;
			}
			var csrftoken = getCookie('csrftoken');
          
          function attachTask(data, prepend){
			var items = data;
			console.log(items)
			var taskHTMLFormat = "<div class=\"form-row\">"
								+		"<div class=\"col-md-3\">Date</div>"
								+		"<div class=\"form-group col-md-9\">"
								+			"<label class=\"form-control\">" + items.date +"</label>"
								+		"</div>"
								+		"<div class=\"col-md-3\">From</div>"
								+		"<div class=\"form-group col-md-3\">"
								+			"<label class=\"form-control\">" + items.location +"</label>"
								+		"</div>"
								+		"<div class=\"col-md-3\">To</div>"
								+		"<div class=\"form-group col-md-3\">"
								+			"<label class=\"form-control\">" + items.destination +"</label>"
								+		"</div>"
								+		"<div class=\"col-md-3\">Depart</div>"
								+		"<div class=\"form-group col-md-3\">"
								+			"<label class=\"form-control\">" + items.dapart +"</label>"
								+		"</div>"
								+		"<div class=\"col-md-3\">Arrive</div>"
								+		"<div class=\"form-group col-md-3\">"
								+			"<label class=\"form-control\">" + items.arrive +"</label>"
								+		"</div>"
                                +		"<div class=\"col-md-3\">Price</div>"
								+		"<div class=\"form-group col-md-9 align-middle\">"
								+			"<label class=\"form-control\">" + items.price +"</label>"
								+		"</div>"
								+		"<div class=\"col-md-3\">Select Seat</div>"
								+		"<div class=\"form-group col-md-9\">"
								+			"<select name=\"seat\" class=\"custom-select\" id=\"inputtripType\" style=\"background-color: rgba(245, 245, 245, 0.4);\">"
								+				"{% for seat in seats %}"
								+					"{% if seat not in booked_seats %}"
								+						"<option value=\"{{seat.id}}\">{{seat.name}}</option>"
								+					"{% endif %}"
								+				"{% endfor %}"
								+			"</select>"
								+		"</div>"
								+		"<div class=\"form-group col-md-12 align-middle\">"
								+			"<button class=\"btn btn-primary btn-xl rounded-pill mt-5\" type=\"submit\">Book</button>"
								+		"</div>"
                  if(prepend ==true){
                    $("#flight-list").prepend(taskHTMLFormat)
                  }else{
                    $("#flight-list").append(taskHTMLFormat)
                  }
          }


          function parseTasks(data){
			attachTask(data)
          }

          function fetchTasks(url){
            var fetchUrl;
            if (!url){
                fetchUrl = '/api/flight/{{flight.id}}/'
            }else{
                fetchUrl = url
            }
            $.ajax({
                url: fetchUrl,
                data: url,
                method: "GET",
                success: function(data){
				newData = JSON.stringify(data)
                taskList = data
                console.log(typeof taskList)
                parseTasks(data)
                },
                error: function(data){
                console.log("error")
                console.log(data)
                }
            })
          }
          fetchTasks()
        });
	</script>
	
{% endblock script %}
{% block title %}{{ block.super }} | Welcome{% endblock title %}
{% block content %}

	<header class="masthead text-center text-white">
		<div class="masthead-content">
            <div class="container">
                <div class="row align-items-center" style="padding:30px;">
                    <div class="col-lg-12">
                        <div class="card style_prevu_kit" style="background-color: rgba(245, 245, 245, 0.4);padding:30px;">
                                <div class="card-block">
                                    <form id="flight-list"  method="post">{% csrf_token %}
                                        <select style="visibility: hidden" name="user" required id="id_user">
                                        <option value="{{user.id}}" selected>{{user.id}}</option>
                                        <option value="{{user.id}}">{{user.id}}</option>
                                        </select></p>
                                        <select name="flight" required id="id_flight" style="visibility: hidden">
                                        <option value="{{flight.id}}" selected>{{flight.id}}</option>
                                        <option value="{{flight.id}}">{{flight.id}}</option>     
                                    </form>
                                </div>
                        </div>
                    </div>
                </div>
            </div>
    </div>
    <div class="bg-circle-1 bg-circle"></div>
    <div class="bg-circle-2 bg-circle"></div>
    <div class="bg-circle-3 bg-circle"></div>
    <div class="bg-circle-4 bg-circle"></div>
</header>

<section>
<div class="container">
<div class="row align-items-center">
    <div class="col-lg-6 order-lg-2">
    <div class="p-5">
        
    </div>
    </div>
    <div class="col-lg-6 order-lg-1">
    <div class="p-5">
        <h2 class="display-4">Our Flights!</h2>
        <p>Flights Our extensive flight network makes travelling the world a breeze.</p> 
        </p>Covering all corners of the globe, we can get you the right flight at the right price without the hassle.</p>
    </div>
    </div>
</div>
</div>
</section>

<section id="services" class="features">
<div class="container">
<div class="row align-items-center">
    <div class="col-lg-4 order-lg-1">
    <div class="feature-item">
        <i class="fas fa-thumbs-up fa-3x"></i>
        <h3>Secure Payment</h3>
        <p>Convenient & reliable booking and payment system!</p>
    </div>
    </div>
    <div class="col-lg-4 order-lg-1">
        <div class="feature-item">
        <i class="fas fa-file fa-3x"></i>
        <h3>One-stop Service</h3>
        <p>Price guaranteed upon confirmed payment, booking guaranteed once tickets issued!</p>
        </div>
    </div>
    <div class="col-lg-4 order-lg-1">
        <div class="feature-item">
        <i class="fas fa-smile fa-3x"></i>
        <h3>Travel at Your Fingertips</h3>
        <p>Manage travel bookings easily through the app, website or by phone!</p>
        </div>
    </div>
    </div>
</div>
</section>


<!-- Footer -->
<footer class="py-5" style="background-color: #133b33">
<div class="container">
<p class="m-0 text-center text-white small">Copyright &copy; Ludaya 2018 <a href="#">  Privacy policy</a> <i class="fab fa-facebook-f fa-2x"></i>  <i class="fab fa-twitter fa-2x"></i>
</div>
<!-- /.container -->
</footer>

{% endblock content %}

templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark navbar-custom fixed-top">
	<div class="container">
		<a class="navbar-brand" href="#">Airtech</a>
		<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
			<span class="navbar-toggler-icon"></span>
		</button>
		<div class="collapse navbar-collapse" id="navbarResponsive">
			<ul class="navbar-nav ml-auto">
			<!-- <li class="nav-item">
				<a class="nav-link" href="#">Blog</a>
			</li> -->
			<li class="nav-item">
				<a class="nav-link  js-scroll-trigger"  data-toggle="modal" data-target="#exampleModal"  href="#"><i class="fas fa-user"></i>Login</a>
			</li>
			<li class="nav-item">
				<a class="nav-link  js-scroll-trigger"  data-toggle="modal" data-target="#registerModal"  href="#"><i class="fas fa-sign-in-alt"></i> Register </a>
			</li>
			</ul>
		</div>
	</div>
</nav>

templates/navbar_login.html
<nav class="navbar navbar-expand-lg navbar-dark navbar-custom fixed-top">
	<div class="container">
		<a class="navbar-brand" href="{% url 'home' %}">Airtech</a>
		<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
			<span class="navbar-toggler-icon"></span>
		</button>
		<div class="collapse navbar-collapse" id="navbarNav">
			<ul class="navbar-nav">
				<li class="nav-item active">
					<a class="nav-link" href="{% url 'index' %}">Search<span class="sr-only">(current)</span></a>
				</li>
				<li class="nav-item">
					<a class="nav-link" href="#">My Flights</a>
				</li>
				<li class="nav-item">
					<a class="nav-link" href="{% url 'profile' %}">My Profile</a>
				</li>
			</ul>
		</div>
		<div class="collapse navbar-collapse" id="navbarResponsive">
			<ul class="navbar-nav ml-auto">
				<li class="nav-item">
					<a href="{% url 'logout' %}?next=/"><i class="fas fa-sign-in-alt"></i> Log Out</a>
				</li>
			</ul>
		</div>
	</div>
</nav>

templates/payment_form.html
{% extends "base.html"  %}
{% block script %}
    <script>
	</script>
	
{% endblock script %}
{% block title %}{{ block.super }} | Welcome{% endblock title %}
{% block content %}

	<header class="masthead text-center text-white">
		<div class="masthead-content">
            <div class="container">
                <div class="row align-items-center" style="padding:30px;">
                    <div class="col-lg-12">
                        <div class="card style_prevu_kit" style="background-color: rgba(245, 245, 245, 0.4);padding:30px;">
                                <div class="card-block">
                                    <form id="flight-list"  method="post">{% csrf_token %}
                                        <h3>Enter Mpesa reference No:</h3>
                                        <select name="booking" style="visibility: hidden" required id="id_booking">
                                            <option value="{{booking}}" selected>{{booking}}</option>
                                        <option value="{{booking}}">{{booking}}</option>
                                        </select></p>
                                        <div class="form-row">
                                            <div class="col-md-3">Date</div>
                                            <div class="form-group col-md-9">
                                                <label class="form-control">{{booking.flight.date}}</label>
                                            </div>
                                            <div class="col-md-3">From</div>
                                            <div class="form-group col-md-3">
                                                <label class="form-control">{{booking.flight.location}}</label>
                                            </div>
                                            <div class="col-md-3">To</div>
                                            <div class="form-group col-md-3">
                                                <label class="form-control">{{booking.flight.destination}}</label>
                                            </div>
                                            <div class="col-md-3">Depart</div>
                                            <div class="form-group col-md-3">
                                                <label class="form-control">{{booking.flight.dapart}}</label>
                                            </div>
                                            <div class="col-md-3">Arrive</div>
                                            <div class="form-group col-md-3">
                                                <label class="form-control">{{booking.flight.arrive}}</label>
                                            </div>
                                            <div class="col-md-3">Price</div>
                                            <div class="form-group col-md-9">
                                                <label class="form-control">{{booking.flight.price}}</label>
                                            </div>
                                            <div class="col-md-3"></div>
                                            <div class="form-group col-md-9">
                                                    <input type="text" class="form-control" id="inputTo" name="payment" placeholder="Enter Payment Reference" style="background-color: rgba(245, 245, 245, 0.4);"  required>
                                            </div>
                                            <div class="form-group col-md-12 align-middle">
                                                <input class="btn btn-primary btn-xl rounded-pill mt-5" type="submit" value="Save">
                                            </div>
                                        </div>
                                    </form>
                                </div>
                        </div>
                    </div>
                </div>
            </div>
    </div>
    <div class="bg-circle-1 bg-circle"></div>
    <div class="bg-circle-2 bg-circle"></div>
    <div class="bg-circle-3 bg-circle"></div>
    <div class="bg-circle-4 bg-circle"></div>
</header>

<section>
<div class="container">
<div class="row align-items-center">
    <div class="col-lg-6 order-lg-2">
    <div class="p-5">
        
    </div>
    </div>
    <div class="col-lg-6 order-lg-1">
    <div class="p-5">
        <h2 class="display-4">Our Flights!</h2>
        <p>Flights Our extensive flight network makes travelling the world a breeze.</p> 
        </p>Covering all corners of the globe, we can get you the right flight at the right price without the hassle.</p>
    </div>
    </div>
</div>
</div>
</section>

<section id="services" class="features">
<div class="container">
<div class="row align-items-center">
    <div class="col-lg-4 order-lg-1">
    <div class="feature-item">
        <i class="fas fa-thumbs-up fa-3x"></i>
        <h3>Secure Payment</h3>
        <p>Convenient & reliable booking and payment system!</p>
    </div>
    </div>
    <div class="col-lg-4 order-lg-1">
        <div class="feature-item">
        <i class="fas fa-file fa-3x"></i>
        <h3>One-stop Service</h3>
        <p>Price guaranteed upon confirmed payment, booking guaranteed once tickets issued!</p>
        </div>
    </div>
    <div class="col-lg-4 order-lg-1">
        <div class="feature-item">
        <i class="fas fa-smile fa-3x"></i>
        <h3>Travel at Your Fingertips</h3>
        <p>Manage travel bookings easily through the app, website or by phone!</p>
        </div>
    </div>
    </div>
</div>
</section>


<!-- Footer -->
<footer class="py-5" style="background-color: #133b33">
<div class="container">
<p class="m-0 text-center text-white small">Copyright &copy; Ludaya 2018 <a href="#">  Privacy policy</a> <i class="fab fa-facebook-f fa-2x"></i>  <i class="fab fa-twitter fa-2x"></i>
</div>
<!-- /.container -->
</footer>

{% endblock content %}

templates/saved.html
<html>
   <body>
   
      {% if saved %}
         <strong>Your profile was saved.</strong>
      {% endif %}
      
      {% if not saved %}
         <strong>Your profile was not saved.</strong>
      {% endif %}
      
   </body>
</html>